name: Release maven package
on:
  workflow_dispatch:

jobs:
  release_maven_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy maven package
        env:
          SIGN_KEY = ${{ secrets.SIGN_KEY }}
          SIGN_KEY_ID = ${{ secrets.SIGN_KEY_ID }}
          SIGN_KEY_PASS = ${{ secrets.SIGN_KEY_PASS }}
        run: |
          mvn \
          -P release \
          -DsonatypeOssDistMgmtSnapshotsUrl=${{ secrets.SONATYPE_OSS_DIST_MGMT_SNAPSHOTS_URL }} \
          -B release:prepare 
