name: Release maven package
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release (x.x.x)
        required: true

jobs:
  release_maven_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update pom version
        run: |
          mvn -B versions:set -DnewVersion=${{ github.event.inputs.tag }} -DgenerateBackupPoms=false

      - name: Setup git config
        run: |
          git config user.name "GitHub Action Bot on behalf of ${{ github.actor }}"
          git config user.email "<>"

      - name: Create release tag
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "Release tag for ${{ github.event.inputs.tag }}"
          git push origin ${{ github.event.inputs.tag }}

      - name: Deploy maven package
        env:
          SIGN_KEY = ${{ secrets.SIGN_KEY }}
          SIGN_KEY_ID = ${{ secrets.SIGN_KEY_ID }}
          SIGN_KEY_PASS = ${{ secrets.SIGN_KEY_PASS }}
        run: |
          mvn \
          -DsonatypeOssDistMgmtSnapshotsUrl= ${{ secrets.sonatypeOssDistMgmtSnapshotsUrl }} \
          clean deploy
